config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'), 
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/<int:question_id>/', comment_views.comment_create, name='comment_create_question'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify_question'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete_question'),
    
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.db.models import QuerySet
from django.conf import settings
from django.contrib.auth.models import User

class Question(models.Model):
    subject     = models.CharField(max_length=200)
    content     = models.TextField()
    author      = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='voter_question')
    def __str__(self):
        return self.subject

    # 클래스메서드 1: 전체 질문 반환
    @classmethod
    def get_all_questions(cls) -> QuerySet['Question']:
        return cls.objects.all()

    # 클래스메서드 2: 최근 N개 질문 반환
    @classmethod
    def get_recent_questions(cls, n: int = 10) -> QuerySet['Question']:
        return cls.objects.order_by('-create_date')[:n]

class Answer(models.Model):
    question    = models.ForeignKey(Question, on_delete=models.CASCADE)
    content     = models.TextField()
    author      = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True,auto_now_add=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='voter_answer')
    def __str__(self):
        return f"Answer to {self.question.id}"

    # 클래스메서드: 특정 질문의 답변들 반환
    @classmethod
    def get_answers_for_question(cls, question_id: int) -> QuerySet['Answer']:
        return cls.objects.filter(question_id=question_id)

    # 함수형: 답변 수 반환 
    def answer_length(self) -> int:
        return len(self.content)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:20]

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from ..forms import AnswerForm
from pybo.services.answer_service import (
    get_answer_by_id,
    create_answer,
    modify_answer,
    delete_answer,
    AnswerNotFound,
)


@login_required(login_url='common:login')
def answer_create(request, question_id):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                answer = create_answer(
                    question_id=question_id,
                    content=data['content'],
                    author=request.user
                )
            except Exception as e:
                messages.error(request, '답변 생성 중 오류가 발생했습니다.')
                return redirect('pybo:detail', question_id=question_id)
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = AnswerForm()
    return render(request, 'pybo/answer_form.html', {'form': form})


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    try:
        answer = get_answer_by_id(answer_id)
    except AnswerNotFound:
        return render(request, 'errors/answer_not_found.html', status=404)

    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            data = form.cleaned_data
            answer = modify_answer(
                answer,
                content=data['content']
            )
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'pybo/answer_form.html', {'form': form})


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    try:
        answer = get_answer_by_id(answer_id)
    except AnswerNotFound:
        return render(request, 'errors/answer_not_found.html', status=404)

    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    delete_answer(answer)
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question


def index(request):
    page = request.GET.get('page', '1') 
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10) 
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from ..forms import CommentForm
from ..models import Question, Answer, Comment


@login_required(login_url='common:login')
def comment_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = CommentForm()
    return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import JsonResponse, HttpResponse, FileResponse
from ..forms import QuestionForm
from ..models import Question
from pybo.services.question_service import (
    get_question_by_id,
    create_question,
    modify_question,
    delete_question,
    QuestionNotFound,
)


def question_list(request):
    questions = Question.objects.order_by('-create_date')
    return render(request, 'pybo/question_list.html', {'question_list': questions})


def question_detail(request, question_id):
    try:
        question = get_question_by_id(question_id)
    except QuestionNotFound:
        return HttpResponse('질문을 찾을 수 없습니다', status=404)

    data = {
        'method': request.method,
        'get_params': request.GET.dict(),
        'user_agent': request.META.get('HTTP_USER_AGENT'),
        'absolute_url': request.build_absolute_uri(),
    }
    return JsonResponse(data)


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            question = create_question(
                subject=data['subject'],
                content=data['content'],
                author=request.user
            )
            attachment = request.FILES.get('attachment')
            if attachment:
                question.attachment.save(attachment.name, attachment)
            request.session['last_qid'] = question.pk
            response = redirect('pybo:index')
            response.set_cookie('last_qid', question.pk)
            return response
    else:
        form = QuestionForm()
    last_qid = request.session.get('last_qid')
    cookie_qid = request.COOKIES.get('last_qid')
    return render(request, 'pybo/question_form.html', {'form': form, 'last_qid': last_qid, 'cookie_qid': cookie_qid})


@login_required(login_url='common:login')
def question_modify(request, question_id):
    try:
        question = get_question_by_id(question_id)
    except QuestionNotFound:
        return HttpResponse('질문을 찾을 수 없습니다', status=404)

    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES, instance=question)
        if form.is_valid():
            data = form.cleaned_data
            question = modify_question(
                question,
                subject=data['subject'],
                content=data['content']
            )
            attachment = request.FILES.get('attachment')
            if attachment:
                question.attachment.save(attachment.name, attachment)
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    return render(request, 'pybo/question_form.html', {'form': form})


@login_required(login_url='common:login')
def question_delete(request, question_id):
    try:
        question = get_question_by_id(question_id)
    except QuestionNotFound:
        return HttpResponse('질문을 찾을 수 없습니다', status=404)

    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    delete_question(question)
    return HttpResponse(status=204)


def download_attachment(request, question_id):
    try:
        question = get_question_by_id(question_id)
    except QuestionNotFound:
        return HttpResponse('질문을 찾을 수 없습니다', status=404)
    attachment = getattr(question, 'attachment', None)
    if not attachment:
        return HttpResponse(status=204)
    file_handle = attachment.open('rb')
    return FileResponse(file_handle, as_attachment=True, filename=attachment.name)

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from ..models import Question, Answer
from pybo.services.vote_service import (
    vote_question_service,
    vote_answer_service,
    QuestionNotFound,
    AnswerNotFound,
    CannotVoteOwnQuestion,
    CannotVoteOwnAnswer,
    AlreadyVoted,
)


@login_required(login_url='common:login')
def vote_question(request, question_id):
    try:
        vote_question_service(question_id, request.user)
    except QuestionNotFound:
        return render(request, 'errors/question_not_found.html', status=404)
    except CannotVoteOwnQuestion:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    except AlreadyVoted:
        messages.error(request, '이미 추천했습니다')
    return redirect('pybo:detail', question_id=question_id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    from pybo.models import Answer  

    try:
        answer = vote_answer_service(answer_id, request.user)
        return redirect('pybo:detail', question_id=answer.question.id)

    except CannotVoteOwnAnswer:
        answer = Answer.objects.get(pk=answer_id)
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    except AlreadyVoted:
        answer = Answer.objects.get(pk=answer_id)
        messages.error(request, '이미 추천했습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    except AnswerNotFound:
        return render(request, 'errors/answer_not_found.html', status=404)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"
               class="recommend save-scroll btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>

                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id  %}"
                           class="save-scroll btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete save-scroll btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                    </div>
                    {% endif %}

                    {# 질문 댓글 영역 (링크 기능 비활성화) #}
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {# 댓글 수정/삭제 링크 비활성화 #}
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small save-scroll">수정</a>,
                            <a href="#" class="small delete save-scroll"
                               data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
                            {% endif %}
                            
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    {# 댓글 추가 링크 비활성화 #}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id  %}"
                           class="small save-scroll"><small>댓글 추가 ..</small></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
               class="recommend save-scroll btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>

                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id  %}"
                           class="save-scroll btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete save-scroll btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}

                    {# 답변 댓글 영역 (링크 기능 비활성화) #}
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {# 댓글 수정/삭제 링크 비활성화 #}
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small save-scroll">수정</a>,
                            <a href="#" class="small delete save-scroll"
                               data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                            
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    {# 댓글 추가 링크 비활성화 #}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id  %}"
                           class="small save-scroll"><small>댓글 추가 ..</small></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3 save-scroll">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    const savedPos = sessionStorage.getItem('questionDetailScroll');
    if (savedPos) {
        $(window).scrollTop(parseInt(savedPos));
        sessionStorage.removeItem('questionDetailScroll');
    }

    $('.save-scroll').on('click', function() {
        sessionStorage.setItem('questionDetailScroll', $(window).scrollTop());
    });
    $('form.save-scroll').on('submit', function() {
        sessionStorage.setItem('questionDetailScroll', $(window).scrollTop());
    });

    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                {% if question.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'pybo:detail' question.id %}" class="detail-link">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

{% block script %}
<script>
$(function() {
    // 저장된 위치가 있으면 페이지 로드 후 이동
    const savedPos = sessionStorage.getItem('questionListScroll');
    if (savedPos) {
        $(window).scrollTop(parseInt(savedPos));
        sessionStorage.removeItem('questionListScroll');
    }

    // 상세 페이지로 이동할 때 현재 스크롤 위치 저장
    $('.detail-link').on('click', function() {
        sessionStorage.setItem('questionListScroll', $(window).scrollTop());
    });
});
</script>
{% endblock %}